// <auto-generated />
using HuRe.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HuRe.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20171219121916_JobDbContext")]
    partial class JobDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HuRe.Models.CongViec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BangCap");

                    b.Property<string>("ChucVu");

                    b.Property<string>("DiaChiLienHe");

                    b.Property<string>("DiaDiem");

                    b.Property<string>("DoTuoi");

                    b.Property<long>("DoanhNghiepId");

                    b.Property<string>("GioiTinh");

                    b.Property<DateTime>("HanNopHoSo");

                    b.Property<long>("HinhThucLamViecId");

                    b.Property<long?>("HinhThucLamViecId1");

                    b.Property<string>("KinhNghiem");

                    b.Property<string>("LuotNopHoSo");

                    b.Property<string>("LuotXem");

                    b.Property<string>("MoTaNgan");

                    b.Property<decimal>("MucLuongCaoNhat");

                    b.Property<decimal>("MucLuongThapNhat");

                    b.Property<DateTime>("NgaySua");

                    b.Property<DateTime>("NgayTao");

                    b.Property<string>("NguoiLienHe");

                    b.Property<string>("QuyenLoi");

                    b.Property<string>("SDTLienHe");

                    b.Property<string>("SoLuong");

                    b.Property<string>("TagNganh");

                    b.Property<string>("ThoiGian");

                    b.Property<string>("ThongTinKhac");

                    b.Property<string>("TieuDe");

                    b.Property<string>("YeuCau");

                    b.HasKey("Id");

                    b.HasIndex("DoanhNghiepId");

                    b.HasIndex("HinhThucLamViecId");

                    b.HasIndex("HinhThucLamViecId1");

                    b.ToTable("CongViecs");
                });

            modelBuilder.Entity("HuRe.Models.DoanhNghiep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiaChi");

                    b.Property<string>("MoTa");

                    b.Property<DateTime>("NgaySua");

                    b.Property<DateTime>("NgayTao");

                    b.Property<string>("NguoiDaiDien");

                    b.Property<long>("NhomViecId");

                    b.Property<long?>("NhomViecId1");

                    b.Property<string>("QuyMo");

                    b.Property<string>("SoDienThoai");

                    b.Property<string>("TenDoanhNghiep");

                    b.Property<string>("TenVietTat");

                    b.Property<string>("URLLogo");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.HasIndex("NhomViecId");

                    b.HasIndex("NhomViecId1");

                    b.ToTable("DoanhNghieps");
                });

            modelBuilder.Entity("HuRe.Models.HinhThucLamViec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("NgaySua");

                    b.Property<DateTime>("NgayTao");

                    b.Property<string>("Tag");

                    b.Property<string>("Ten");

                    b.Property<string>("TenVietTat");

                    b.HasKey("Id");

                    b.ToTable("HinhThucLamViecs");
                });

            modelBuilder.Entity("HuRe.Models.HoSoCaNhan", b =>
                {
                    b.Property<long>("Id");

                    b.Property<Guid>("TaiKhoanId");

                    b.Property<string>("DiaDiem");

                    b.Property<long>("HinhThucLamViecId");

                    b.Property<long?>("HinhThucLamViecId1");

                    b.Property<string>("KinhNghiem");

                    b.Property<DateTime>("NgaySua");

                    b.Property<DateTime>("NgayTao");

                    b.Property<long>("NhomViecId");

                    b.Property<long?>("NhomViecId1");

                    b.Property<string>("TrinhDo");

                    b.Property<string>("ViTriTimViec");

                    b.HasKey("Id", "TaiKhoanId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("HinhThucLamViecId");

                    b.HasIndex("HinhThucLamViecId1");

                    b.HasIndex("NhomViecId");

                    b.HasIndex("NhomViecId1");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("HoSoCaNhans");
                });

            modelBuilder.Entity("HuRe.Models.NhomViec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MoTa");

                    b.Property<DateTime>("NgaySua");

                    b.Property<DateTime>("NgayTao");

                    b.Property<string>("Tag");

                    b.Property<string>("Ten");

                    b.Property<string>("URLHinhanh");

                    b.Property<string>("VietTat");

                    b.HasKey("Id");

                    b.ToTable("NhomViecs");
                });

            modelBuilder.Entity("HuRe.Models.PhanQuyen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MoTa");

                    b.Property<DateTime>("NgaySua");

                    b.Property<DateTime>("NgayTao");

                    b.Property<long?>("PhanQuyenId");

                    b.Property<string>("Ten");

                    b.HasKey("Id");

                    b.HasIndex("PhanQuyenId");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("HuRe.Models.SuKien", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiaDiem");

                    b.Property<string>("MoTaNgan");

                    b.Property<DateTime>("NgaySua");

                    b.Property<DateTime>("NgayTao");

                    b.Property<string>("NoiDung");

                    b.Property<string>("Ten");

                    b.Property<DateTime>("ThoiGianBatDau");

                    b.Property<DateTime>("ThoiGianKetThuc");

                    b.Property<string>("TieuDe");

                    b.HasKey("Id");

                    b.ToTable("SuKiens");
                });

            modelBuilder.Entity("HuRe.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnhDaiDien");

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<bool>("GioiTinh");

                    b.Property<string>("Ho");

                    b.Property<string>("Lop");

                    b.Property<string>("MatKhau");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<long>("PhanQuyenId");

                    b.Property<string>("SDT");

                    b.Property<string>("Ten");

                    b.Property<string>("TenTaiKhoan");

                    b.HasKey("Guid");

                    b.HasIndex("PhanQuyenId");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("HuRe.Models.CongViec", b =>
                {
                    b.HasOne("HuRe.Models.DoanhNghiep", "DoanhNghiep")
                        .WithMany()
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HuRe.Models.HinhThucLamViec", "HinhThucLamViec")
                        .WithMany()
                        .HasForeignKey("HinhThucLamViecId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HuRe.Models.HinhThucLamViec")
                        .WithMany("CongViecs")
                        .HasForeignKey("HinhThucLamViecId1");
                });

            modelBuilder.Entity("HuRe.Models.DoanhNghiep", b =>
                {
                    b.HasOne("HuRe.Models.NhomViec", "NhomViec")
                        .WithMany()
                        .HasForeignKey("NhomViecId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HuRe.Models.NhomViec")
                        .WithMany("DoanhNghieps")
                        .HasForeignKey("NhomViecId1");
                });

            modelBuilder.Entity("HuRe.Models.HoSoCaNhan", b =>
                {
                    b.HasOne("HuRe.Models.HinhThucLamViec", "HinhThucLamViec")
                        .WithMany()
                        .HasForeignKey("HinhThucLamViecId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HuRe.Models.HinhThucLamViec")
                        .WithMany("HoSoCaNhans")
                        .HasForeignKey("HinhThucLamViecId1");

                    b.HasOne("HuRe.Models.NhomViec", "NhomViec")
                        .WithMany()
                        .HasForeignKey("NhomViecId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HuRe.Models.NhomViec")
                        .WithMany("HoSoCaNhans")
                        .HasForeignKey("NhomViecId1");

                    b.HasOne("HuRe.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HuRe.Models.PhanQuyen", b =>
                {
                    b.HasOne("HuRe.Models.PhanQuyen")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("PhanQuyenId");
                });

            modelBuilder.Entity("HuRe.Models.TaiKhoan", b =>
                {
                    b.HasOne("HuRe.Models.PhanQuyen", "PhanQuyen")
                        .WithMany()
                        .HasForeignKey("PhanQuyenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
